### PR TITLE
RadioCo v3.0?

### PR DESCRIPTION
**Pull request by stefan-walluhn**
Hi Iago,

I'd like to find a way to merge back all the changes I made to RadioCo to use this software at RadioCorax. We are starting to use RadioCo right now. I consider the code being in beta status.

There was one change that renamed the the root folder from radio -> radioco to make this package a valid python egg. Unfortunately, this change prevent this pull request from being a proper changeset, but only deletes one folder and adds another one :-(

To solve the situation I'd like to propose the following steps: Since there are tons of changes including some major ones like rrules based scheduling and a new API, it is valid to bump to version 3.0. I am not into the details if there is heavy development on the current master branch. If so, maybe we just start a v3.0 branch? If not, is it an option for you to make the step to v3.0?

In any case, I expect we need some rounds of bugfixing and stabilization together with Chema.

### CODE REVIEW

**Comment by stefan-walluhn** [comment]
Travis failed, I'll have a look.

**Comment by stefan-walluhn** [comment]
Seems several Django extensions are incompatible with Django < 1.8. Django 1.8 is green. How to proceed?

**Comment by iago1460** [comment]
Great job! I will take a look this weekend.

Don't worry about support multiple library versions I just wanted to try Travis.

**Comment by iago1460** [comment]
Thanks for this, the [develop branch](https://github.com/iago1460/django-radio/tree/develop) is going to hold the current development until the next version is released.

**Pull request closed without merging**
